#!/usr/bin/env python3
"""Expert Sourcing Agent — CLI.

Examples
--------
  # Zero-setup demo (offline, synthetic data):
  python cli.py --demo

  # Live run (needs internet; OpenAlex needs no key):
  python cli.py "large language model alignment" --limit 10

  # Add Claude-authored profiles + outreach:
  export ANTHROPIC_API_KEY=sk-ant-...
  python cli.py "computational biology" --limit 8 --out results/

  # Seed from Nobel laureates in a category:
  python cli.py --nobel physics --limit 15
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

# make `expert_agent` importable when run from the repo root
sys.path.insert(0, str(Path(__file__).resolve().parent))

from expert_agent import LLMClient, run_candidates, run_live   # noqa: E402
from expert_agent.models import Candidate, Contact, Evidence, Expert  # noqa: E402

DEFAULT_CFG = {
    "llm": {"provider": "anthropic", "model": "claude-sonnet-4-6"},
    "search": {"provider": "tavily"},
    "outreach": {
        "sender_name": "[Your Name]",
        "sender_role": "Expert Network, Surge AI",
        "offer": "paid, flexible, and built around your schedule",
        "ask": "a 20-minute intro call",
    },
}


def load_config(path: str | None) -> dict:
    cfg = json.loads(json.dumps(DEFAULT_CFG))  # deep copy
    if path and Path(path).exists():
        try:
            import yaml
            with open(path) as f:
                user = yaml.safe_load(f) or {}
            for k, v in user.items():
                if isinstance(v, dict):
                    cfg.setdefault(k, {}).update(v)
                else:
                    cfg[k] = v
        except Exception as e:
            print(f"(config: using defaults — {e})")
    return cfg


def load_dotenv_if_present() -> None:
    try:
        from dotenv import load_dotenv
        load_dotenv()
    except Exception:
        pass


def candidates_from_sample(path: str) -> tuple[list[Candidate], str]:
    data = json.loads(Path(path).read_text())
    cands = []
    for row in data["experts"]:
        cands.append(Candidate(
            expert=Expert(**row["expert"]),
            evidence=Evidence(**row.get("evidence", {})),
            contact=Contact(**row.get("contact", {})),
        ))
    return cands, data.get("field", "the field")


# ---------- output ----------
def print_table(cands: list[Candidate]) -> None:
    try:
        from rich.console import Console
        from rich.table import Table
        t = Table(title="Ranked Experts", header_style="bold")
        for col in ("#", "Name", "Institution", "Fit", "Rel", "Snr", "Rsp", "Rch", "Nobel", "Contact"):
            t.add_column(col)
        for i, c in enumerate(cands, 1):
            s = c.scores
            t.add_row(str(i), c.expert.name, (c.expert.institution or "")[:28],
                      f"{s.get('fit_total',0):.2f}", f"{s.get('relevance',0):.2f}",
                      f"{s.get('seniority',0):.2f}", f"{s.get('responsiveness',0):.2f}",
                      f"{s.get('reachability',0):.2f}", "★" if c.expert.is_nobel_laureate else "",
                      c.contact.best_channel or "—")
        Console().print(t)
        return
    except Exception:
        pass
    # plain fallback
    print("\n  #  Fit   Name                      Institution                 Contact")
    print("  " + "-" * 78)
    for i, c in enumerate(cands, 1):
        star = " ★" if c.expert.is_nobel_laureate else ""
        print(f"  {i:<2} {c.fit_total:>4.2f}  {c.expert.name[:24]:<24}  "
              f"{(c.expert.institution or '')[:26]:<26}  {c.contact.best_channel or '—'}{star}")


def write_reports(cands: list[Candidate], field: str, out: Path) -> None:
    out.mkdir(parents=True, exist_ok=True)
    (out / "results.json").write_text(
        json.dumps([c.to_dict() for c in cands], indent=2, ensure_ascii=False))

    lines = [f"# Expert shortlist — {field}\n",
             f"_{len(cands)} candidates, ranked by fit. Generated by Expert Sourcing Agent._\n"]
    for i, c in enumerate(cands, 1):
        e, p, o = c.expert, c.profile, c.outreach
        lines.append(f"\n## {i}. {e.name}"
                     + (f"  ·  {e.nobel_detail}" if e.is_nobel_laureate else ""))
        lines.append(f"**{e.institution or 'Unknown institution'}** · "
                     f"{e.cited_by_count:,} citations · h-index {e.h_index} · "
                     f"**fit {c.fit_total:.2f}**")
        lines.append(f"\n{p.summary}")
        if p.fit_for_ai_feedback:
            lines.append(f"\n**Why they fit AI-feedback work:** {p.fit_for_ai_feedback}")
        if p.talking_points:
            lines.append("\n**Personalization hooks:**")
            lines += [f"- {tp}" for tp in p.talking_points]
        ch = c.contact
        contact_str = ch.email or (ch.links[0] if ch.links else "—")
        lines.append(f"\n**Contact ({ch.best_channel or 'n/a'}):** {contact_str}")
        if ch.email_source:
            lines.append(f"_source: {ch.email_source}_")
        if o:
            lines.append(f"\n**Draft outreach**\n\n> **Subject:** {o.subject}\n>")
            for para in o.body.split("\n"):
                lines.append(f"> {para}")
        lines.append("\n---")
    (out / "report.md").write_text("\n".join(lines))
    print(f"\nWrote {out/'report.md'} and {out/'results.json'}")


def main() -> None:
    ap = argparse.ArgumentParser(description="Find, profile, and reach domain experts for AI-feedback work.")
    ap.add_argument("field", nargs="?", help='e.g. "large language model alignment"')
    ap.add_argument("--limit", type=int, default=10)
    ap.add_argument("--nobel", metavar="CATEGORY",
                    help="physics|chemistry|medicine|economics|literature|peace")
    ap.add_argument("--demo", action="store_true", help="offline run on synthetic sample data")
    ap.add_argument("--config", default="config.yaml")
    ap.add_argument("--out", default="results")
    args = ap.parse_args()

    load_dotenv_if_present()
    cfg = load_config(args.config)

    if args.demo:
        print("Running in DEMO mode (offline, synthetic data, templated LLM output).\n")
        llm = LLMClient(mock=True)
        cands, field = candidates_from_sample(
            str(Path(__file__).parent / "examples" / "sample_experts.json"))
        cands = run_candidates(cands, llm, cfg, field_terms=field.split())
    elif args.nobel and not args.field:
        from expert_agent import discover
        print(f"Fetching Nobel laureates in {args.nobel}…")
        experts = discover.find_laureates(args.nobel, limit=args.limit)
        cands = run_candidates([Candidate(expert=e) for e in experts],
                               LLMClient(model=cfg["llm"]["model"]), cfg,
                               field_terms=[args.nobel])
        field = f"Nobel laureates — {args.nobel}"
    elif args.field:
        llm = LLMClient(model=cfg["llm"]["model"])
        if llm.mock:
            print("(No ANTHROPIC_API_KEY found — profiles/outreach use offline templates.)\n")
        cands = run_live(args.field, args.limit, llm, cfg, nobel_category=args.nobel)
        field = args.field
    else:
        ap.print_help()
        sys.exit(0)

    if not cands:
        print("No candidates produced.")
        sys.exit(0)

    print_table(cands)
    write_reports(cands, field, Path(args.out))
    top = cands[0]
    if top.outreach:
        print(f"\nTop pick: {top.expert.name} — draft subject: “{top.outreach.subject}”")


if __name__ == "__main__":
    main()
